// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_source/events.proto

package events;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.events.Type type = 1;</code>
   */
  events.Type getType();

  /**
   * <code>int32 hour = 2;</code>
   */
  int getHour();

  /**
   * <code>int32 minute = 3;</code>
   */
  int getMinute();

  /**
   * <code>int32 second = 4;</code>
   */
  int getSecond();

  /**
   * <code>string name = 5;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 5;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string years = 6;</code>
   */
  java.util.List<java.lang.String>
      getYearsList();
  /**
   * <code>repeated string years = 6;</code>
   */
  int getYearsCount();
  /**
   * <code>repeated string years = 6;</code>
   */
  java.lang.String getYears(int index);
  /**
   * <code>repeated string years = 6;</code>
   */
  com.google.protobuf.ByteString
      getYearsBytes(int index);
}
