// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_source/events.proto

package events;

public final class EventsProto {
  private EventsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_TypeArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_TypeArg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto_source/events.proto\022\006events\"m\n\004D" +
      "ata\022\032\n\004type\030\001 \001(\0162\014.events.Type\022\014\n\004hour\030" +
      "\002 \001(\005\022\016\n\006minute\030\003 \001(\005\022\016\n\006second\030\004 \001(\005\022\014\n" +
      "\004name\030\005 \001(\t\022\r\n\005years\030\006 \003(\t\"*\n\007TypeArg\022\037\n" +
      "\teventType\030\001 \001(\0162\014.events.Type*\034\n\004Type\022\010" +
      "\n\004TIME\020\000\022\n\n\006DEVICE\020\0012@\n\014EventService\0220\n\t" +
      "Subscribe\022\017.events.TypeArg\032\014.events.Data" +
      "\"\000(\0010\001B\027\n\006eventsB\013EventsProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_events_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_Data_descriptor,
        new java.lang.String[] { "Type", "Hour", "Minute", "Second", "Name", "Years", });
    internal_static_events_TypeArg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_events_TypeArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_TypeArg_descriptor,
        new java.lang.String[] { "EventType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
