// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_source/events.proto

package events;

public interface TypeArgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.TypeArg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events.Type eventType = 1;</code>
   */
  int getEventTypeValue();
  /**
   * <code>.events.Type eventType = 1;</code>
   */
  events.Type getEventType();
}
