# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/events.proto',
  package='events',
  syntax='proto3',
  serialized_pb=_b('\n\x12proto/events.proto\x12\x06\x65vents\"m\n\x04\x44\x61ta\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.events.Type\x12\x0c\n\x04hour\x18\x02 \x01(\x05\x12\x0e\n\x06minute\x18\x03 \x01(\x05\x12\x0e\n\x06second\x18\x04 \x01(\x05\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\r\n\x05years\x18\x06 \x03(\t\"*\n\x07TypeArg\x12\x1f\n\teventType\x18\x01 \x01(\x0e\x32\x0c.events.Type*\x1c\n\x04Type\x12\x08\n\x04TIME\x10\x00\x12\n\n\x06\x44\x45VICE\x10\x01\x32@\n\x0c\x45ventService\x12\x30\n\tSubscribe\x12\x0f.events.TypeArg\x1a\x0c.events.Data\"\x00(\x01\x30\x01\x42\x17\n\x06\x65ventsB\x0b\x45ventsProtoP\x01\x62\x06proto3')
)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='events.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TIME', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=185,
  serialized_end=213,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
TIME = 0
DEVICE = 1



_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='events.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='events.Data.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hour', full_name='events.Data.hour', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minute', full_name='events.Data.minute', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second', full_name='events.Data.second', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='events.Data.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='years', full_name='events.Data.years', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=139,
)


_TYPEARG = _descriptor.Descriptor(
  name='TypeArg',
  full_name='events.TypeArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventType', full_name='events.TypeArg.eventType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=183,
)

_DATA.fields_by_name['type'].enum_type = _TYPE
_TYPEARG.fields_by_name['eventType'].enum_type = _TYPE
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['TypeArg'] = _TYPEARG
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'proto.events_pb2'
  # @@protoc_insertion_point(class_scope:events.Data)
  ))
_sym_db.RegisterMessage(Data)

TypeArg = _reflection.GeneratedProtocolMessageType('TypeArg', (_message.Message,), dict(
  DESCRIPTOR = _TYPEARG,
  __module__ = 'proto.events_pb2'
  # @@protoc_insertion_point(class_scope:events.TypeArg)
  ))
_sym_db.RegisterMessage(TypeArg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\006eventsB\013EventsProtoP\001'))

_EVENTSERVICE = _descriptor.ServiceDescriptor(
  name='EventService',
  full_name='events.EventService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=215,
  serialized_end=279,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='events.EventService.Subscribe',
    index=0,
    containing_service=None,
    input_type=_TYPEARG,
    output_type=_DATA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSERVICE)

DESCRIPTOR.services_by_name['EventService'] = _EVENTSERVICE

# @@protoc_insertion_point(module_scope)
